version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    steps:
      - run:
          name: Configure and setup DEIS...
          command: |
            echo "These steps should happen first so we can get some time for the ECR registry to update..."
            echo "Add deis-builder to known_hosts..."
            ssh-keyscan -p 2222 -H deis-builder.$DEIS_HOME >> ~/.ssh/known_hosts
            echo "Download and install DEIS..."
            curl -sSL http://deis.io/deis-cli/install-v2.sh | bash
            sudo mv $PWD/deis /usr/local/bin/deis
            echo "Login to our DEIS infrastructure..."
            deis login http://deis.$DEIS_HOME --username $DEIS_USER --password $DEIS_PASS
            echo "Create our app pod if it does not exist already..."
            set +e
            export DEIS_NAME=${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}
            deis create --no-remote $DEIS_NAME
            echo "Send our App ENV vars to that pod..."
            env | grep DEIS_ENV | sed 's/DEIS_ENV_*//g' | xargs deis config:set --app=$DEIS_NAME

      - run:
          name: Update and do installs into environment...
          command: |
            sudo apt-get update
            # sudo apt-get install -y git vim wget libfreetype6-dev libjpeg62-turbo-dev libpng-dev zip unzip
            # sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
            # sudo docker-php-ext-install pdo_mysql bcmath gd exif zip
      - checkout
      - run:
          name: Deploy to our pod...
          command: |
            export DEIS_NAME=${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}
            git push ssh://git@deis-builder.$DEIS_HOME:2222/$DEIS_NAME.git $CIRCLE_SHA1:refs/heads/master -f
            # - deis run rake db:migrate -a $DEIS_NAME
            # - deis ps:restart -a $DEIS_NAME

workflows:
  version: 2
  pull-requests:
    jobs:
      - build


