FROM mysql:5.7

ENV TZ="UTC"

RUN apt-get install -y tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN dpkg-reconfigure --frontend noninteractive tzdata

COPY ./sql/*.sql /docker-entrypoint-initdb.d/
